final List<String> mysticFortunes = [
  "🔮 The universe whispers… yes.",
  "🧠 Seek truth within yourself.",
  "😅 You’ll laugh about this someday.",
  "🦄 Time bends to your wish.",
  "🔮 Energy flows in your favor.",
  "🧠 You already know the answer.",
  "😅 Don’t bet your snacks on it.",
  "🦄 Reality just glitched — try again.",
  "🔮 The answer is shimmering nearby.",
  "🧠 Bold questions get bold answers.",
  "🌌 Stars align for you tonight.",
  "🐉 A wild journey awaits you.",
  "⚡ You hold more power than you know.",
  "🎲 Luck spins in your favor now.",
  "🔥 A spark today ignites tomorrow's fire.",
  "🌙 Dream boldly, the cosmos listens.",
  "🕊️ Peace follows your next choice.",
  "🎯 Focus: your target is within reach.",
  "🌪️ The winds of change swirl near.",
  "🧃 Sip slowly. The truth is strong today.",
  "👁️ What you seek also seeks you.",
  "🧊 Chill. Things will cool down soon.",
  "🌞 Light is coming — hang in there.",
  "👻 A ghost from the past may visit.",
  "💡 Brilliant ideas brew in your mind.",
  "🎡 Life spins — enjoy the highs.",
  "📦 Expect the unexpected in strange packaging.",
  "🐸 Leap — the lily pad is closer than it seems.",
  "🧩 Pieces will fall into place soon.",
  "🚪 A mysterious door is about to open.",
  "🪐 Cosmic forces are rearranging for you.",
  "🐢 Slow and steady will charm the stars.",
  "🎐 Answers will arrive on the breeze.",
  "🧭 Your inner compass is pointing true north.",
  "🌈 Good vibes are headed your way.",
  "🐾 Follow the small signs — they matter.",
  "💭 What you're dreaming now matters tomorrow.",
  "🪞 The reflection holds a clue.",
  "📜 Destiny has scribbled something new.",
  "🛸 You’re being watched… in a good way.",
  "🎩 A little magic goes a long way.",
  "🕰️ Timing is everything — and it’s lining up.",
  "🌱 Patience will sprout powerful results.",
  "🥸 Trust your instincts — even the weird ones.",
  "🍀 Something lucky is brewing for you.",
  "🗝️ The key is already in your pocket.",
  "🚀 You’re closer to lift-off than you think.",
  "🦉 Wisdom will visit when silence does.",
  "🌊 Go with the flow — it’s guiding you.",
  "🪄 Your thoughts are casting spells. Choose well.",
  "🥁 A surprise beat is about to drop.",
  "📡 The universe just pinged you: message incoming.",
  "🍿 Popcorn moments ahead. Watch closely.",
  "🧶 The tangled mess hides something golden.",
  "🛤️ You’re on track — even if it feels odd.",
  "🫧 Clarity is rising like bubbles. Wait for it.",
  "🎭 Not all masks hide — some protect.",
  "🍂 Let go of the old to catch the breeze.",
  "🔐 What’s locked isn’t lost. Just waiting.",
  "🎇 A spark of wonder will find you soon.",
  "🎤 Speak — the stars are listening.",
  "🌌 The night holds more than shadows.",
  "🌟 Your moment is unfolding — slowly, surely.",
  "🦋 Transformation is whispering from within.",
  "🚦Green light ahead — go boldly.",
  "🎮 You’re the main player. Press start.",
  "🧪 A little risk creates big change.",
  "🎈 Let go. Float free for a while.",
  "🧱 A wall is a puzzle, not an end.",
  "🎻 Harmony follows your next step.",
];
